server:
  port: 8081
spring:
  application:
    name: center-auth
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    database: 0
    port: 16379
    host: localhost
    password: root
