server:
  port: 8800
spring:
  application:
    name: nocas-user-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'